### ISSUE TITLE
Request Permission Loop

### ISSUE THREAD

**Issue by JeanHuit** [GDGGhana/ShortCode#2]
There's a section of the code that is not implemented properly. i.e the request permission for phone calls.
Now, although this is novel and all. I do not believe this code is necessary. This is because its the only permission needed in the app, without which the app is useless. Thus, the mere fact that you installed the app means, you want to have the ability to make calls in case of emergency. Now, the "permission request kept popping up after every change of activity/layout. 
I simply solved this via removing that piece of code. The manifest already had the necessary  line of code  to make calling work. 

Now if and when additional permissions are required, like storage and camera use, then the app could adopt the the initial strategy.

I believe the optional permissions are there for requirements that are optional, without which the app will still work.

**Comment by kennyung6** [comment]
Absolutely right Mr @JeanHuit , we were planning to fix that. we actually detected that Bug before announcing the alpha version but prototype release deadline constrained us.

Anyways, thanks for fixing the issue. i will just sync the repo to validate the changes.
